fix: disable "Restart Tale" when Tale is stopped
whole-tale/ngx-dashboard pull request #207
Opened 2021-06-23 08:08 UTC by bodom0015

## Problem
"Restart Tale" is offered even when Tale is not running

Fixes #199 

## Approach
* Hide this option from the dropdown
* Also make the icon spacing consistent on this dropdown (it was bothering me)

NOTE: I tried simply disabling this option, but that doesn't allow me to show a tooltip since it is `disabled` ... so there was no way how to let the user know why the item was disabled.

## How to Test
Prerequisites: at least one Tale created, not running

1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Navigate to Run Tale for a stopped Tale
4. Expand the dropdown at the top-right
    * You should **not** see the "Restart Tale" option listed here
5. Run the Tale, wait for Tale to fully start (e.g. `instance.status === 1`)
6. Expand the dropdown again
    * You should see the "Restart Tale" option is now listed here

2021-07-02 19:16 UTC, craig-willis requested changes

2021-07-02 19:16 UTC, craig-willis commented on src/app/+run-tale/run-tale/run-tale.component.html
> +                                            <div class="item" (click)="restartTale()" *ngIf="isTaleWritable() && instance && instance.status === -1">
```suggestion
                                            <div class="item" (click)="restartTale()" *ngIf="isTaleWritable() && instance && instance.status === 1">

```

Shouldn't this be 1?

2021-07-06 15:42 UTC, bodom0015 commented on src/app/+run-tale/run-tale/run-tale.component.html
> +                                            <div class="item" (click)="restartTale()" *ngIf="isTaleWritable() && instance && instance.status === -1">
Good catch! Indeed, this should probably be a 1

This is why I shouldn't make PRs at 3AM :X lol

2021-07-19 15:28 UTC, Xarthisius approved these changes

2021-07-21 19:53 UTC, craig-willis approved these changes

2021-07-26 21:19 UTC, merged