feat: add move-to-dialog for changing parent folder
whole-tale/ngx-dashboard pull request #98
Opened 2020-08-31 16:12 UTC by bodom0015

## Problem
The MoveTo dialog was never implemented. There is already some code written that can work as a callback that this modal should execute after submission.

## Approach
* Implement the MoveToDialog, allowing user to change the parent folder of a given file or folder

* NOTE: This approach currently encounters issues when moving from a Tale Workspace to Home, and vice versa. I may be missing some bits about setting `baseParentId` properly when shifting between data sources.

## How to Test
Prerequisites: at least one Tale created, at least two folders created

1. Checkout this branch locally, rebuild the dashboard
2. Login to the WholeTale Dashboard
3. Create a Tale, if you haven't already
4. Navigate to Run > Files > Home or Run > Files > Tale Workspace
5. Create two folders here, called "Folder A" and "Folder B"
6. Expand the dropdown beside "Folder B" and choose "Move To..."
    * You should see the MoveToDialog now appear
    * You should be offered a file browser with "Home" and "Tale Workspaces" at the top level
7. Click into Tale Workspaces
    * You should see the names of all Tales listed here
    * Hovering over a Tale name, you should see its ID
8. Double-click (not click) a Tale name to navigate into its Workspace
    * You should **not** be able to select "Tale Workspaces" - this prevents the users from selecting it as a destination
    * You should be brought into the Workspace
    * You should see the Tale's name at the top of the file browser, indicating that you can click it to navigate back up
    * You should not be able to select any files (they are disabled).. only folders are allowed
9. Click the blue header / up arrow twice to go back to the root
10. Double-click Home to navigate into it
    * You should see the contents of your Home folder are listed here
    * You should not be able to select any files (they are disabled).. only folders are allowed
11. Choose / select "Folder A" using single-click, and then click Confirm
    * You should see the modal now close
    * You should see your file disappear from the parent file browser view (it has moved!)
12. Navigate into "Folder A"
    * You should see "Folder B" sitting here

2020-09-10 17:33 UTC, Xarthisius requested changes
Moving doesn't work for item/files right now. I highlighted the problem inline.

2020-09-10 17:33 UTC, Xarthisius commented on src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
> +    const params = { id: src._id, parentId: dest._id, parentType: ParentType.Folder, baseParentId: dest.baseParentId };
These parameters only apply to folders (`parentId` and `parentType` in particular), yet they're passed as an argument to `this.itemService.itemUpdateItem()` below. `PUT /item/:id` will expect `folderId` as new target.

2020-09-11 15:37 UTC, bodom0015 commented on src/app/+run-tale/run-tale/tale-files/tale-files.component.ts
> +    const params = { id: src._id, parentId: dest._id, parentType: ParentType.Folder, baseParentId: dest.baseParentId };
Whoops, had not noticed the difference in parameter name.. Good catch!

Will push a fix for this ASAP :+1:

2020-09-17 18:15 UTC, Xarthisius approved these changes
Works like a charm! With the addition of `virtual_resources` it's also possible to move in between `Home` and `Workspaces` as expected.

2020-09-18 16:00 UTC, ThomasThelen approved these changes

2020-09-18 16:00 UTC, merged